// This file is generated by `@sdeverywhere/plugin-config`; do not edit manually!

import type { GraphSpec, InputSpec } from './spec-types'

export const graphSpecs: GraphSpec[] = [
  {
    "id": "1",
    "kind": "line",
    "titleKey": "graph_001_title",
    "xMin": 2012,
    "xMax": 2042,
    "yMin": 0,
    "yFormat": ".0f",
    "datasets": [
      {
        "varId": "_placed_on_market",
        "varName": "Placed on market",
        "labelKey": "graph_dataset_label__placed_on_market",
        "color": "#0072b2",
        "lineStyle": "line"
      },
      {
        "varId": "_waste_generated",
        "varName": "Waste generated",
        "labelKey": "graph_dataset_label__waste_generated",
        "color": "#d33700",
        "lineStyle": "line"
      },
      {
        "varId": "_waste_collected",
        "varName": "Waste collected",
        "labelKey": "graph_dataset_label__waste_collected",
        "color": "#53bb37",
        "lineStyle": "line"
      }
    ],
    "legendItems": [
      {
        "color": "#0072b2",
        "labelKey": "graph_dataset_label__placed_on_market"
      },
      {
        "color": "#d33700",
        "labelKey": "graph_dataset_label__waste_generated"
      },
      {
        "color": "#53bb37",
        "labelKey": "graph_dataset_label__waste_collected"
      }
    ]
  }
]

export const inputSpecs: InputSpec[] = [
  {
    "kind": "slider",
    "id": "1",
    "varId": "_la_collected_household",
    "varName": "la collected household",
    "defaultValue": 0.5,
    "minValue": -0.5,
    "maxValue": 1.5,
    "step": 0.1,
    "reversed": false,
    "labelKey": "input_001_label",
    "unitsKey": "input_units__units",
    "rangeLabelKeys": [],
    "rangeDividers": [],
    "format": ".0f"
  }
]
