// This file is generated by `@sdeverywhere/plugin-config`; do not edit manually!
export const inputVarIds: string[] = [
  "_la_collected_household"
]
export const outputVarIds: string[] = [
  "_placed_on_market",
  "_waste_collected",
  "_waste_generated"
]
