require(readxl)
require(plyr)
require(dplyr)
require(tidyverse)
require(magrittr)
require(knitr)
require(ggplot2)
require(forecast)

# Import the data
pom_data_indicators <- read_xlsx( 
           "./cleaned_data/packaging_pom_indicators.xlsx") %>%
  filter(material == "plastic",
         variable == "Selling",
         year != "2024") %>%
  select(1,7)

# Calculate ratio to population 
# Import the baseline data
download.file(
  "https://www.ons.gov.uk/generator?format=xls&uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/timeseries/ukpop/pop",
  "./raw_data/population_outturn.xls"
)

population_outturn <- 
  read_excel("./raw_data/population_outturn.xls", sheet = 1) %>%
  select(1,2) %>%
  row_to_names(7) %>%
  rename(year = 1,
         population = 2)

population_ratio <-
  dplyr::left_join(# Join the correspondence codes and the trade data
    pom_data_indicators,
    population_outturn,
    by =join_by("year")) %>%
  na.omit() %>%
  mutate_at(c('POM','population'), as.numeric) %>%
  mutate(pom_per_capita = POM/population)

rmc <- read_excel("./raw_data/rmc.xlsx", sheet = 1) 
rmcts <- ts(rmc,frequency=1,start=c(2000,1))
rmclin <- tslm(rmcts ~ trend)
rmclinforecast <- forecast(rmclin, h=15)

autoplot(rmclinforecast) +
  ggtitle("Linear RMC forecast (including fossil fuels)") +
  ylab("tonnes")

summary(rmclinforecast)

# Coefficients:
# (Intercept)        trend  
#      884179        15814  

# ME     RMSE      MAE      MPE     MAPE    MASE      ACF1
# Training set 0.00000000001662721 113603.8 97859.32 -1.14901 8.963208 1.87011 0.8014378

checkresiduals(rmclin)

# Breusch-Godfrey test for serial correlation of order up to 6

# data:  Residuals from Linear regression model
# LM test = 20.166, df = 6, p-value = 0.002588

## Linear Model (Ex FF)

rmcex <- read_excel("rmc.xlsx", sheet = 4) 
rmcexts <- ts(rmcex,frequency=1,start=c(1990,1))
rmcexlin <- tslm(rmcexts ~ trend)
rmcexlinforecast <- forecast(rmcexlin, h=33)
autoplot(rmcexlinforecast) +
  ggtitle("Linear RMC forecast (excluding fossil fuels)") +
  ylab("tonnes")

write.csv(print(rmcexlinforecast), file = 'linex.csv')

# ME     RMSE     MAE       MPE     MAPE     MASE      ACF1
# Training set  0 82569.64 71423.2 -1.204567 8.923005 1.701615 0.7861153

#SES 

rmc3 <- read_excel("rmc.xlsx", sheet = 1) 
rmcts3 <- ts(rmc3,frequency=1,start=c(1990,1))
rmcses <- ses(rmcts3, h=33, level =c(95))
plot(rmcses)

## Holts Exponential Smoothing

#Import data and format as time series
rmc3 <- read_excel("rmc.xlsx", sheet = 1) 
rmcts3 <- ts(rmc3,frequency=1,start=c(1990,1))

#Product Holt ES
rmcholt <- holt(rmcts3, h=33, level = c(95))

#Produce a damped Holt ES
# The forecasts generated by Holt’s linear method display a constant trend (increasing or decreasing) indefinitely into the future. Empirical evidence indicates that these methods tend to over-forecast, especially for longer forecast horizons. Motivated by this observation, Gardner & McKenzie (1985) introduced a parameter that “dampens” the trend to a flat line some time in the future. 
rmcholtalt98 <- holt(rmcts3, damped=TRUE, phi = 0.98, h=33)
rmcholtalt97 <- holt(rmcts3, damped=TRUE, phi = 0.97, h=33)
rmcholtalt96 <- holt(rmcts3, damped=TRUE, phi = 0.96, h=33)
rmcholtalt95 <- holt(rmcts3, damped=TRUE, phi = 0.95, h=33)

e1 <- tsCV(rmcts3, tslm, h=1)

e2 <- tsCV(rmcts3, holt, h=1)
e3 <- tsCV(rmcts3, holt, damped=TRUE, phi = 0.98, h=1)
e4 <- tsCV(rmcts3, holt, damped=TRUE, phi = 0.97, h=1)
e5 <- tsCV(rmcts3, holt, damped=TRUE, phi = 0.96, h=1)
e6 <- tsCV(rmcts3, holt, damped=TRUE, phi = 0.95, h=1)

mean(e1^2, na.rm=TRUE)

mean(e2^2, na.rm=TRUE)
#> [1] 8283689268
mean(e3^2, na.rm=TRUE)
#> [1] 7974066034
mean(e4^2, na.rm=TRUE)
#> [1] 7863281039 - best
mean(e5^2, na.rm=TRUE)
#> [1] 9940133751
mean(e6^2, na.rm=TRUE)
#> [1] 9756816450

# Compare MAE:
mean(abs(e2), na.rm=TRUE)
#> [1] 65017.87
mean(abs(e3), na.rm=TRUE)
#> [1] 64681.13
mean(abs(e4), na.rm=TRUE)
#> [1] 64584.64- best
mean(abs(e5), na.rm=TRUE)
#> [1] 72048.39
mean(abs(e6), na.rm=TRUE)
#> [1] 71842.96

autoplot(rmcts3) +
  autolayer(rmcholt, series="Holt's ES", PI=FALSE) +
  autolayer(rmcholtalt97, series="Damped Holt's method", PI=FALSE) +
  ggtitle("Forecasts") + 
  xlab("Year") +
  ylab("RMC") 

autoplot(rmcts3) +
  autolayer(rmcholtalt97, series="Damped Holt's method", PI=TRUE) +
  ggtitle("Damped Holt's method") + 
  xlab("Year") +
  ylab("RMC") 

accuracy(rmcholtalt97)

# ME     RMSE      MAE        MPE     MAPE      MASE      ACF1
# Training set -5181.252 70007.58 51091.53 -0.6710249 4.787047 0.9763687 0.1322787

```

# Exponential smoothing (Inc FF)
etsnormal <- ets(rmcts3, damped = TRUE)
# AIC     AICc      BIC 
# 723.2512 724.2512 727.2478 

ets98 <- ets(rmcts3, damped =TRUE, phi=0.98)
# AIC     AICc      BIC 
# 728.1933 730.9206 734.8544 

# ME     RMSE      MAE        MPE     MAPE      MASE      ACF1
# Training set -304.2518 69810.16 51896.06 -0.2343661 4.838882 0.9917434 0.1338486

ets97 <- ets(rmcts3, damped =TRUE, phi=0.97)
# AIC     AICc      BIC 
# 728.0578 730.7851 734.7188 

# ME     RMSE      MAE        MPE     MAPE      MASE      ACF1
# Training set -5181.248 70007.58 51091.54 -0.6710244 4.787047 0.9763688 0.1322789

ets96 <- ets(rmcts3, damped =TRUE, phi=0.96)
# AIC     AICc      BIC 
# 727.9685 730.6958 734.6295 

ets95 <- ets(rmcts3, damped =TRUE, phi=0.95)
# AIC     AICc      BIC 
# 727.9216 730.6489 734.5827 

ets98fcast <- forecast(etsnormal, h=32) 

autoplot(ets98fcast) +
  ggtitle("Exponential Smoothing RMC forecast (including fossil fuels)") +
  ylab("tonnes")

write.csv(print(ets98fcast), file = 'etsfcast.csv')

## Multivariate Model (GDP & Pop)

rmc2 <- read_excel("rmc.xlsx", sheet = 2) 
rmcts2 <- ts(rmc2,frequency=1,start=c(1998,1))
mvm <- tslm(RMC ~ Population + GDP, data = rmcts2)
summary(mvm)
accuracy(mvm)

## Resource Productivity (Holt Damped)

```{r}
RPholtd <- read_excel("holtdampedinput.xlsx", sheet = 1) 
RPholtdd <- RPholtd %>% mutate(CentralRP = GDP/Point) %>% mutate(Low95RMC = GDP/Lo95)  %>% mutate(High95RMC = GDP/Hi95)
RPholtdd$Point <- NULL
RPholtdd$Lo80 <- NULL
RPholtdd$Hi80 <- NULL
RPholtdd$Lo95 <- NULL
RPholtdd$Hi95 <- NULL
RPholtdd$GDP <- NULL
view(RPholtdd)

ggplot(RPholtdd) +
  geom_line(aes(Year, Outturn), color = "black") +
  geom_line(aes(Year, CentralRP), color = "blue") +
  geom_line(aes(Year, Low95RMC), color = "green") +
  geom_line(aes(Year, High95RMC), color = "red")

write.csv(print(RPholtdd), file = 'holtRP.csv')

## By Material Type

bymat <- read_excel("rmc.xlsx", sheet = 3)
biomassts <- ts(bymat$Biomass,frequency=1,start=c(1990,1))
orests <- ts(bymat$Ores,frequency=1,start=c(1990,1))
NMMMts <- ts(bymat$NMMM,frequency=1,start=c(1990,1))
FFts <- ts(bymat$FFs,frequency=1,start=c(1990,1))

matlinbio <- tslm(biomassts ~ trend) 
matlinbiof <- forecast(matlinbio, h=33)
matlinore <- tslm(orests ~ trend)
matlinoref <- forecast(matlinore, h=33)
matlinNMMM <- tslm(NMMMts ~ trend)
matlinNMMMf <- forecast(matlinNMMM, h=33)
matlinFF <- tslm(FFts ~ trend)
matlinFFf <- forecast(matlinFF, h=33)

plot(matlinbiof)
plot(matlinoref)
plot(matlinNMMMf)
plot(matlinFFf)

download.file(
  "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationprojections/datasets/tablea11principalprojectionuksummary/2021basedinterim/ukpppsummary.xlsx",
  "./raw_data/population_projections.xlsx"
)
